# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build for Windows
      run: |
        cd src
        GOOS=windows GOARCH=amd64 go build -o ../go-pownMyHash_Win64.exe -v ./...

    - name: Build for Unix/Linux
      run: |
        cd src
        GOOS=linux GOARCH=amd64 go build -o ../go-pownMyHash_Unix64.bin -v ./...

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: go-pownMyHash_Win64
        path: go-pownMyHash_Win64.exe
        retention-days: 7

    - name: Upload Unix/Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: go-pownMyHash_Unix64
        path: go-pownMyHash_Unix64.bin
        retention-days: 7
